/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUAnnounceNotificationSettingsItemProvider : HFItemProvider {
    NSMutableSet * _items;
    HMUser * _user;
}

@property (nonatomic, readonly) NSMutableSet *items;
@property (nonatomic, readonly) HMUser *user;

- (void).cxx_destruct;
- (id)init;
- (id)initWithUser:(id)arg1;
- (id)invalidationReasons;
- (id)items;
- (id)reloadItems;
- (id)user;

@end
