/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUInformationalServiceGridViewController : HUServiceGridViewController <HUServiceGridItemManagerDelegate> {
    id /* block */  _filter;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) id /* block */ filter;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)configureCell:(id)arg1 forItem:(id)arg2;
- (id /* block */)filter;
- (id)init;
- (id)layoutOptionsForSection:(long long)arg1;
- (bool)presentationCoordinator:(id)arg1 shouldBeginInteractivePresentationWithTouchLocation:(struct CGPoint { double x1; double x2; })arg2;
- (bool)serviceGridItemManager:(id)arg1 shouldHideItem:(id)arg2;
- (void)setFilter:(id /* block */)arg1;

@end
