/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitInvocation.framework/SiriKitInvocation
 */

@interface SKIPhoneInvocation : NSObject

+ (id)announceHomeAnnouncementRequestFromApp:(id)arg1;
+ (id)readHomeAnnouncementRequestFromApp:(id)arg1;

@end
