/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHLibraryAdditionalItemsIndicatorIcon : SBFolderIcon {
    SBHLibraryCategory * _category;
}

@property (nonatomic, readonly) SBHLibraryCategory *category;

- (void).cxx_destruct;
- (id)category;
- (id)initWithCategory:(id)arg1;
- (bool)isAdditionalItemsIndicatorIcon;

@end
