/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHTableViewController : UITableViewController {
    NSArray * _centerNoResultsFoundLabelConstraints;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _keyboardFrame;
    UIView * _noResultsView;
    bool  _showNoResultsView;
    long long  _styleBeforeShowingNoResults;
}

@property (nonatomic, retain) UIView *noResultsView;
@property (nonatomic) bool showNoResultsView;

+ (Class)tableViewClass;

- (void).cxx_destruct;
- (void)_addAutolayoutConstraintsForNoResultsFoundLabel;
- (double)_calculateVerticalMultiplierForKeyboard;
- (void)_keyboardWillDismiss:(id)arg1;
- (void)_keyboardWillResize:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_reloadNoResultsFoundLabelForKeyboardNotification:(id)arg1;
- (void)_removeAutolayoutConstraintsForNoResultsFoundLabel;
- (void)_resetNoResultsView;
- (id)noResultsView;
- (void)setNoResultsView:(id)arg1;
- (void)setShowNoResultsView:(bool)arg1;
- (bool)showNoResultsView;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
