/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface _NCNotificationBannerRequestContextDefiningViewController : UIViewController

- (bool)_canShowWhileLocked;
- (void)addChildViewController:(id)arg1;
- (id)customBackgroundContainerViewForExpandedPlatterPresentationController:(id)arg1;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;

@end
