/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UserNotificationsUIKit.framework/UserNotificationsUIKit
 */

@interface NCCarPlayBannerSource : NSObject <BNBannerSourceDelegate, BNBannerSourceProvidingPrivate, BNPresentableObserving> {
    BNBannerSource * _bannerSource;
    BSTimer * _dismissTimer;
    NSPointerArray * _postedPresentables;
    BSTimer * _replaceTimer;
    <BNBannerSourceDelegate> * delegate;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <BNBannerSourceDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) long long destination;
@property (getter=_dismissTimer, setter=_setDismissTimer:, nonatomic, retain) BSTimer *dismissTimer;
@property (readonly) unsigned long long hash;
@property (getter=_replaceTimer, setter=_setReplaceTimer:, nonatomic, retain) BSTimer *replaceTimer;
@property (nonatomic, readonly, copy) NSString *requesterIdentifier;
@property (readonly) Class superclass;
@property (getter=isValid, nonatomic, readonly) bool valid;

+ (void)initialize;

- (void).cxx_destruct;
- (void)_allPresentablesDidDisappear;
- (id)_bannerSource;
- (void)_cancelDismissTimer;
- (void)_cancelReplaceTimer;
- (id)_dismissTimer;
- (void)_enqueuePostedPresentable:(id)arg1;
- (unsigned long long)_indexOfPostedPresentable:(id)arg1;
- (bool)_isPresentableSticky:(id)arg1;
- (id)_peekPostedPresentable;
- (unsigned long long)_postedPresentableCount;
- (id)_postedPresentablesWithRequestIdentifier:(id)arg1;
- (void)_presentableDidDisappear:(id)arg1;
- (void)_presentableWithRequestIdentifierDidDisappear:(id)arg1;
- (id)_pullPostedPresentableAtIndex:(unsigned long long)arg1;
- (id)_replaceTimer;
- (void)_revokePreviouslyPostedPresentableIfPossible;
- (void)_setDismissTimer:(id)arg1;
- (void)_setReplaceTimer:(id)arg1;
- (bool)_setSuspended:(bool)arg1 forReason:(id)arg2 revokingCurrent:(bool)arg3;
- (void)_startDismissTimer;
- (void)_startReplaceTimer;
- (void)bannerSourceDidInvalidate:(id)arg1;
- (id)delegate;
- (long long)destination;
- (void)invalidate;
- (bool)isValid;
- (id)keyWindowForScreen:(id)arg1;
- (id)layoutDescriptionWithError:(out id*)arg1;
- (bool)postPresentable:(id)arg1 options:(unsigned long long)arg2 userInfo:(id)arg3 error:(out id*)arg4;
- (void)presentableDidAppearAsBanner:(id)arg1;
- (void)presentableDidDisappearAsBanner:(id)arg1 withReason:(id)arg2;
- (id)requesterIdentifier;
- (bool)revokeAllPresentablesWithReason:(id)arg1 userInfo:(id)arg2 error:(out id*)arg3;
- (bool)revokePresentableWithRequestIdentifier:(id)arg1 animated:(bool)arg2 reason:(id)arg3 userInfo:(id)arg4 error:(out id*)arg5;
- (void)setDelegate:(id)arg1;
- (bool)setSuspended:(bool)arg1 forReason:(id)arg2 revokingCurrent:(bool)arg3 error:(out id*)arg4;

@end
