/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFCompactDialogViewController : WFCompactPlatterViewController {
    <WFCompactDialogViewControllerDelegate> * _delegate;
    WFDialogRequest * _request;
}

@property (nonatomic) <WFCompactDialogViewControllerDelegate> *delegate;
@property (nonatomic, readonly) WFDialogRequest *request;

+ (id)interfaceActionForDialogButton:(id)arg1 handler:(id /* block */)arg2;

- (void).cxx_destruct;
- (bool)canHandleFollowUpRequest:(id)arg1;
- (void)configureActionGroupWithActions:(id)arg1;
- (id)delegate;
- (void)finishWithResponse:(id)arg1;
- (void)finishWithResponse:(id)arg1 waitForFollowUpRequest:(bool)arg2;
- (void)handleFollowUpRequest:(id)arg1;
- (id)initWithRequest:(id)arg1;
- (void)loadView;
- (id)request;
- (void)setDelegate:(id)arg1;

@end
