/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDataAccessDomain : PTDomain

+ (id)domainGroupName;
+ (id)domainName;
+ (id)rootSettings;
+ (Class)rootSettingsClass;

@end
