/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDataAccessSettings : PTSettings {
    bool  _alwaysShowIndicatorForCameraCapture;
    bool  _alwaysShowIndicatorForMicrophoneCapture;
    long long  _indicatorColor;
}

@property (nonatomic) bool alwaysShowIndicatorForCameraCapture;
@property (nonatomic) bool alwaysShowIndicatorForMicrophoneCapture;
@property long long indicatorColor;

+ (id)settingsControllerModule;

- (bool)alwaysShowIndicatorForCameraCapture;
- (bool)alwaysShowIndicatorForMicrophoneCapture;
- (long long)indicatorColor;
- (void)setAlwaysShowIndicatorForCameraCapture:(bool)arg1;
- (void)setAlwaysShowIndicatorForMicrophoneCapture:(bool)arg1;
- (void)setDefaultValues;
- (void)setIndicatorColor:(long long)arg1;

@end
