/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPIPMorphAnimatorController : NSObject <SBViewMorphAnimatorObserver> {
    id /* block */  _animatorWaitingForExternalAnimationActionBlock;
    long long  _completedTargetAnimations;
    <SBPIPMorphAnimatorControllerDelegate> * _delegate;
    PGPictureInPictureViewController * _pictureInPictureViewController;
    id /* block */  _setupCompletionBlock;
    long long  _startedSourceAnimations;
    NSUUID * _uuid;
    SBViewMorphAnimator * _viewMorphAnimator;
    SBPIPMorphAnimatorDataSource * _viewMorphAnimatorDataSource;
}

@property (nonatomic, copy) id /* block */ animatorWaitingForExternalAnimationActionBlock;
@property (nonatomic) long long completedTargetAnimations;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBPIPMorphAnimatorControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) PGPictureInPictureViewController *pictureInPictureViewController;
@property (nonatomic, copy) id /* block */ setupCompletionBlock;
@property (nonatomic) long long startedSourceAnimations;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSUUID *uuid;
@property (nonatomic, readonly) SBViewMorphAnimator *viewMorphAnimator;
@property (nonatomic, readonly) SBPIPMorphAnimatorDataSource *viewMorphAnimatorDataSource;

- (void).cxx_destruct;
- (bool)_isWaitingForExternalAnimationCompletion;
- (void)_terminate;
- (id /* block */)animatorWaitingForExternalAnimationActionBlock;
- (void)animatorWasInterrupted:(id)arg1;
- (void)cancel;
- (long long)completedTargetAnimations;
- (id)delegate;
- (void)didEndSourceAnimations:(unsigned long long)arg1 finished:(bool)arg2 continueBlock:(id /* block */)arg3;
- (void)didEndTargetAnimations:(unsigned long long)arg1 finished:(bool)arg2 continueBlock:(id /* block */)arg3;
- (id)init;
- (id)initWithTargetProcessIdentifier:(int)arg1 uuid:(id)arg2 scenePersistenceIdentifier:(id)arg3 direction:(long long)arg4 gestureInitiated:(bool)arg5;
- (void)interrupt;
- (bool)isContentFromFillGravity;
- (id)pictureInPictureViewController;
- (id)scenePersistenceIdentifier;
- (void)setAnimatorWaitingForExternalAnimationActionBlock:(id /* block */)arg1;
- (void)setCompletedTargetAnimations:(long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setPictureInPictureViewController:(id)arg1;
- (void)setSetupCompletionBlock:(id /* block */)arg1;
- (void)setStartedSourceAnimations:(long long)arg1;
- (id /* block */)setupCompletionBlock;
- (long long)startedSourceAnimations;
- (int)targetProcessIdentifier;
- (id)uuid;
- (id)viewMorphAnimator;
- (id)viewMorphAnimatorDataSource;
- (void)willStartSourceAnimations:(unsigned long long)arg1;

@end
