/* Generated by RuntimeBrowser.
 */

@protocol _INPBReadAnnouncementIntent <NSObject>

@required

- (int)StringAsReadType:(NSString *)arg1;
- (bool)hasIntentMetadata;
- (bool)hasReadType;
- (_INPBIntentMetadata *)intentMetadata;
- (int)readType;
- (NSString *)readTypeAsString:(int)arg1;
- (void)setHasReadType:(bool)arg1;
- (void)setIntentMetadata:(_INPBIntentMetadata *)arg1;
- (void)setReadType:(int)arg1;

@end
