/* Generated by RuntimeBrowser.
 */

@protocol ANAnnounceServiceInterface <NSObject>

@required

- (void)announcementForID:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 7: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, void*
- (void)broadcastReply:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)broadcastReply:(void *)arg1 forAnnouncement:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSURL *, ANAnnouncement *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)broadcastReply:(void *)arg1 forAnnouncementID:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSURL *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)contextFromAnnouncement:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 7: ANAnnouncement *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncementContext *, void*
- (void)getReceivedAnnouncementsWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)getScanningDeviceCandidates:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSSet *, void*
- (void)getUnplayedAnnouncementsWithCompletionHandler:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)homeNamesForContext:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 7: ANHomeContext *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)isLocalDeviceInRoom:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 7: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, void*
- (void)lastPlayedAnnouncementInfo:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSDictionary *, void*
- (void)localParticipant:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANParticipant *, void*
- (void)mockAnnouncement:(void *)arg1 forHomeWithName:(void *)arg2 playbackDeadline:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 10: NSURL *, NSString *, NSDate *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)prewarm:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*
- (void)receivedAnnouncementIDs:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)sendAnnouncement:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)sendAnnouncement:(void *)arg1 toHomeWithID:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSURL *, NSUUID *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)sendAnnouncement:(void *)arg1 toHomeWithName:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSURL *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)sendAnnouncement:(void *)arg1 toRoomsWithIDs:(void *)arg2 andZonesWithIDs:(void *)arg3 inHomeWithID:(void *)arg4 completion:(void *)arg5; // needs 5 arg types, found 11: NSURL *, NSArray *, NSArray *, NSUUID *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)sendAnnouncement:(void *)arg1 toRoomsWithNames:(void *)arg2 andZonesWithNames:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 10: NSURL *, NSArray *, NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)sendAnnouncement:(void *)arg1 toRoomsWithNames:(void *)arg2 andZonesWithNames:(void *)arg3 inHomeWithName:(void *)arg4 completion:(void *)arg5; // needs 5 arg types, found 11: NSURL *, NSArray *, NSArray *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*
- (void)sendReply:(void *)arg1 forAnnouncement:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSURL *, ANAnnouncement *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ANAnnouncement *, NSError *, void*

@end
