/* Generated by RuntimeBrowser.
 */

@protocol ANConnectionDelegate <NSObject>

@required

- (void)connection:(id <ANConnectionProvider>)arg1 didReceiveMessage:(NSDictionary *)arg2 fromSender:(ANSender *)arg3 senderContext:(ANSenderContext *)arg4;
- (void)connection:(id <ANConnectionProvider>)arg1 failedDeliveryForMessage:(NSDictionary *)arg2 withError:(NSError *)arg3;

@end
