/* Generated by RuntimeBrowser.
 */

@protocol HAP2AccessoryServerPrivate <HAP2AccessoryServer>

@required

- (<HAP2AccessoryServerBrowserPrivate> *)browser;
- (<HAP2AccessoryServerControllerPrivate> *)controller;
- (HAP2SerializedOperationQueue *)operationQueue;

@end
