/* Generated by RuntimeBrowser.
 */

@protocol SBRootFolderViewLayoutManager <NSObject>

@required

- (void)layoutSubviews;
- (SBRootFolderView *)rootFolderView;
- (void)setRootFolderView:(SBRootFolderView *)arg1;
- (void)transitionToActive:(bool)arg1 usingAnimator:(id <UIViewImplicitlyAnimating>)arg2;

@end
