/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CarPlaySupport.framework/CarPlaySupport
 */

@interface CPSPointOfInterestAnnotationView : MKAnnotationView {
    CPImageSet * _imageSet;
}

@property (nonatomic, retain) CPImageSet *imageSet;

- (void).cxx_destruct;
- (id)imageSet;
- (void)setImageSet:(id)arg1;
- (void)setSelected:(bool)arg1;
- (void)setSelected:(bool)arg1 animated:(bool)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)update;

@end
