/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftCore.dylib
 */

@interface _TtCs12_SwiftObject <NSObject> {
    Class  isa;
    struct RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> > { 
        struct atomic<swift::RefCountBitsT<swift::RefCountIsInline> > { 
            struct __cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline> > > { 
                _Atomic struct RefCountBitsT<swift::RefCountIsInline> {} __a_value; 
            } __a_; 
        } refCounts; 
    }  refCounts;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

// Image: /usr/lib/swift/libswiftCore.dylib

+ (bool)_isDeallocating;
+ (bool)_tryRetain;
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (bool)allowsWeakReference;
+ (id)autorelease;
+ (Class)class;
+ (bool)conformsToProtocol:(id)arg1;
+ (id)debugDescription;
+ (id)description;
+ (void)initialize;
+ (int (*)instanceMethodForSelector:(SEL)arg1;
+ (bool)instancesRespondToSelector:(SEL)arg1;
+ (bool)isMemberOfClass:(Class)arg1;
+ (bool)isSubclassOfClass:(Class)arg1;
+ (int (*)methodForSelector:(SEL)arg1;
+ (void)release;
+ (bool)respondsToSelector:(SEL)arg1;
+ (id)retain;
+ (unsigned long long)retainCount;
+ (bool)retainWeakReference;
+ (Class)superclass;

- (unsigned long long)_cfTypeID;
- (id)_copyDescription;
- (bool)_isDeallocating;
- (void)_noteAssociatedObjects;
- (void)_setWeaklyReferenced;
- (bool)_tryRetain;
- (bool)allowsWeakReference;
- (id)autorelease;
- (Class)class;
- (bool)conformsToProtocol:(id)arg1;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (bool)isKindOfClass:(Class)arg1;
- (bool)isMemberOfClass:(Class)arg1;
- (bool)isNSArray__;
- (bool)isNSCFConstantString__;
- (bool)isNSData__;
- (bool)isNSDate__;
- (bool)isNSDictionary__;
- (bool)isNSNumber__;
- (bool)isNSObject__;
- (bool)isNSOrderedSet__;
- (bool)isNSSet__;
- (bool)isNSString__;
- (bool)isNSTimeZone__;
- (bool)isNSValue__;
- (bool)isProxy;
- (int (*)methodForSelector:(SEL)arg1;
- (id)performSelector:(SEL)arg1;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (oneway void)release;
- (bool)respondsToSelector:(SEL)arg1;
- (id)retain;
- (unsigned long long)retainCount;
- (bool)retainWeakReference;
- (id)self;
- (Class)superclass;
- (struct _NSZone { }*)zone;

// Image: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib

+ (id)flex_allClassMethods;
+ (id)flex_allClassProperties;
+ (id)flex_allInstanceMethods;
+ (id)flex_allInstanceProperties;
+ (id)flex_allIvars;
+ (id)flex_allMethods;
+ (id)flex_allProperties;
+ (id)flex_allSubclasses;
+ (id)flex_classHierarchy;
+ (id)flex_classMethodNamed:(id)arg1;
+ (id)flex_classPropertyNamed:(id)arg1;
+ (id)flex_concreteGlobalsEntry:(unsigned long long)arg1;
+ (unsigned long long)flex_instanceSize;
+ (id)flex_ivarNamed:(id)arg1;
+ (Class)flex_metaclass;
+ (id)flex_methodNamed:(id)arg1;
+ (id)flex_propertyNamed:(id)arg1;
+ (id)flex_protocols;
+ (id)flex_reflection;
+ (void)flex_replaceProperty:(id)arg1;
+ (void)flex_replaceProperty:(id)arg1 attributes:(id)arg2;
+ (Class)flex_setSuperclass:(Class)arg1;

- (void*)flex_getIvarAddress:(id)arg1;
- (void*)flex_getIvarAddressByName:(id)arg1;
- (void*)flex_getObjcIvarAddress:(struct objc_ivar { }*)arg1;
- (id)flex_reflection;
- (Class)flex_setClass:(Class)arg1;
- (void)flex_setIvar:(id)arg1 object:(id)arg2;
- (void)flex_setIvar:(id)arg1 value:(void*)arg2 size:(unsigned long long)arg3;
- (bool)flex_setIvarByName:(id)arg1 object:(id)arg2;
- (bool)flex_setIvarByName:(id)arg1 value:(void*)arg2 size:(unsigned long long)arg3;
- (void)flex_setObjcIvar:(struct objc_ivar { }*)arg1 object:(id)arg2;
- (void)flex_setObjcIvar:(struct objc_ivar { }*)arg1 value:(void*)arg2 size:(unsigned long long)arg3;

// Image: /usr/lib/libobjc.A.dylib

+ (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
