/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceShortcutsUICardKitProviderSupport.framework/VoiceShortcutsUICardKitProviderSupport
 */

@interface VSUIAsyncLoadingCard : CRBasicCard {
    <CRCard> * _storedCard;
}

- (void).cxx_destruct;
- (bool)asynchronous;
- (id)initWithCard:(id)arg1;
- (void)loadCardWithCompletion:(id /* block */)arg1;

@end
