/* Generated by RuntimeBrowser
   Image: /usr/lib/libcolorpicker.dylib
 */

@interface PFColorAlert : NSObject <HBColorPickerDelegate> {
    UIColor * _color;
    id /* block */  _completion;
    bool  _showAlpha;
    PFColorAlert * _strongSelf;
    HBColorPickerViewController * _viewController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)colorAlertWithStartColor:(id)arg1 showAlpha:(bool)arg2;

- (void).cxx_destruct;
- (void)close;
- (void)colorPicker:(id)arg1 didSelectColor:(id)arg2;
- (void)colorPickerDidCancel:(id)arg1;
- (void)displayWithCompletion:(id /* block */)arg1;
- (id)initWithStartColor:(id)arg1 showAlpha:(bool)arg2;

@end
