/* Generated by RuntimeBrowser
   Image: /usr/lib/libcolorpicker.dylib
 */

@interface PFColorCell : PFLiteColorCell

- (id)_hbcp_default;
- (id)_hbcp_defaults;
- (id)_hbcp_key;
- (id)_hbcp_postNotification;
- (bool)_hbcp_supportsAlpha;

@end
