/* Generated by RuntimeBrowser
   Image: /usr/lib/libcolorpicker.dylib
 */

@interface PFLiteColorCell : HBColorPickerTableCell

- (id)_colorValue;
- (id)_hbcp_default;
- (id)_hbcp_defaults;
- (id)_hbcp_key;
- (id)_hbcp_postNotification;
- (bool)_hbcp_supportsAlpha;
- (void)_setColorValue:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end
