/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantSettingsSupport.framework/AssistantSettingsSupport
 */

@interface AssistantDetailController : PSListController {
    NSMutableSet * _disabledLockScreenBundles;
    NSMutableSet * _disabledSpotlightApps;
    NSMutableSet * _disabledSpotlightBundles;
    NSMutableSet * _disabledSpotlightShortcuts;
    NSMutableSet * _disabledSuggestApps;
    PSSpecifier * _onHomeScreenGroup;
    PSSpecifier * _onHomeScreenShowAppSpecifier;
    PSSpecifier * _onHomeScreenShowContentSpecifier;
    PSSpecifier * _onHomeScreenSuggestAppSpecifier;
    PSSpecifier * _onHomeScreenSuggestShortcutsSpecifier;
    PSSpecifier * _onLockScreenGroup;
    PSSpecifier * _onLockScreenShowSiriSuggestionsSpecifier;
}

- (void).cxx_destruct;
- (void)_addInAppSpecifiersToSpecifiers:(id)arg1;
- (void)_addonHomeScreenSpecifiersToSpecifiers:(id)arg1;
- (id)_appName;
- (void)_asyncAddAskSiriSettingsIfNecessary;
- (id)_bundleId;
- (id)_enableSiriAppSpecifiersWithAppId:(id)arg1 accessGranted:(bool)arg2;
- (void)_fetchIntentsSpecifiersWithCompletion:(id /* block */)arg1;
- (id)_inAppFooterString;
- (id)_inAppShowToggleLableString;
- (id)_loadDisabledShortcutsSet;
- (id)_loadDisabledSuggestAppsSet;
- (void)_saveOnHomeScreenShowAppEnabled:(bool)arg1;
- (void)_saveOnHomeScreenShowContentEnabled:(bool)arg1;
- (void)_saveOnHomeScreenSuggestAppEnabled:(bool)arg1;
- (void)_saveOnHomeScreenSuggestShortcutsEnabled:(bool)arg1;
- (void)_saveOnLockScreenShowSiriSuggestionsEnabled:(bool)arg1;
- (bool)_showLockscreenGroup;
- (id)_siriSuggestionsClients;
- (id)_watchBundleToMirrorWithBundleId:(id)arg1;
- (id)askSiriUseWithAskSiriEnabled:(id)arg1;
- (id)inAppLearnFromAppEnabled:(id)arg1;
- (id)inAppShowSiriSuggestionsEnabled:(id)arg1;
- (id)onHomeScreenShowAppEnabled:(id)arg1;
- (id)onHomeScreenShowContentEnabled:(id)arg1;
- (id)onHomeScreenSuggestAppEnabled:(id)arg1;
- (id)onHomeScreenSuggestShortcutsEnabled:(id)arg1;
- (id)onLockScreenShowSiriSuggestionsEnabled:(id)arg1;
- (void)setAskSiriUseWithAskSiriEnabled:(id)arg1 specifier:(id)arg2;
- (void)setInAppLearnFromAppEnabled:(id)arg1 specifier:(id)arg2;
- (void)setInAppShowSiriSuggestionsEnabled:(id)arg1 specifier:(id)arg2;
- (void)setNanoInAppShowSiriSuggestionsEnabled:(bool)arg1 bundleId:(id)arg2;
- (void)setOnHomeScreenShowAppEnabled:(id)arg1 specifier:(id)arg2;
- (void)setOnHomeScreenShowContentEnabled:(id)arg1 specifier:(id)arg2;
- (void)setOnHomeScreenSuggestAppEnabled:(id)arg1 specifier:(id)arg2;
- (void)setOnHomeScreenSuggestShortcutsEnabled:(id)arg1 specifier:(id)arg2;
- (void)setOnLockScreenShowSiriSuggestionsEnabled:(id)arg1 specifier:(id)arg2;
- (id)specifiers;
- (void)viewWillAppear:(bool)arg1;

@end
