/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANAnalyticsAssistant : NSObject <ANAnalyticsAssistantProtocol>

- (id)_playerForAnnouncement:(id)arg1;
- (struct ANAnalyticsAssistantAudioData { unsigned long long x1; double x2; })audioDataForAnnouncement:(id)arg1;
- (long long)boundGroupCount:(long long)arg1;
- (struct ANAnalyticsAssistantSenderData { unsigned long long x1; int x2; unsigned long long x3; unsigned long long x4; })senderDataForAnnouncement:(id)arg1;

@end
