/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANAnnounceServer : NSObject {
    ANAnnounceServiceListener * _announceServiceListener;
    ANPlaybackSessionServiceListener * _playbackSessionServiceListener;
    ANRapportEventStreamHandler * _rapportEventStreamHandler;
}

@property (nonatomic, readonly) ANAnnounceServiceListener *announceServiceListener;
@property (nonatomic, readonly) ANPlaybackSessionServiceListener *playbackSessionServiceListener;
@property (nonatomic, readonly) ANRapportEventStreamHandler *rapportEventStreamHandler;

+ (id)sharedServer;

- (void).cxx_destruct;
- (id)announceServiceListener;
- (id)init;
- (id)playbackSessionServiceListener;
- (id)rapportEventStreamHandler;

@end
