/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANAnnounceServiceListener : NSObject <ANAnnounceServiceDelegate, ANAnnounceServiceInterface, NSXPCListenerDelegate> {
    ANAnnounceService * _announceService;
    NSXPCListener * _listener;
}

@property (nonatomic, readonly) ANAnnounceService *announceService;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSXPCListener *listener;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_handleError:(long long)arg1 completion:(id /* block */)arg2;
- (id)announceService;
- (void)announcementForID:(id)arg1 reply:(id /* block */)arg2;
- (void)broadcastReply:(id)arg1 completion:(id /* block */)arg2;
- (void)broadcastReply:(id)arg1 forAnnouncement:(id)arg2 completion:(id /* block */)arg3;
- (void)broadcastReply:(id)arg1 forAnnouncementID:(id)arg2 completion:(id /* block */)arg3;
- (void)contextFromAnnouncement:(id)arg1 reply:(id /* block */)arg2;
- (void)failedToDeliverAnnouncement:(id)arg1 error:(id)arg2;
- (void)getReceivedAnnouncementsWithCompletionHandler:(id /* block */)arg1;
- (void)getScanningDeviceCandidates:(id /* block */)arg1;
- (void)getUnplayedAnnouncementsWithCompletionHandler:(id /* block */)arg1;
- (void)homeNamesForContext:(id)arg1 reply:(id /* block */)arg2;
- (id)init;
- (void)isLocalDeviceInRoom:(id)arg1 reply:(id /* block */)arg2;
- (void)lastPlayedAnnouncementInfo:(id /* block */)arg1;
- (id)listener;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)localParticipant:(id /* block */)arg1;
- (void)mockAnnouncement:(id)arg1 forHomeWithName:(id)arg2 playbackDeadline:(id)arg3 completion:(id /* block */)arg4;
- (void)prewarm:(id /* block */)arg1;
- (void)receivedAnnouncement:(id)arg1;
- (void)receivedAnnouncementIDs:(id /* block */)arg1;
- (void)sendAnnouncement:(id)arg1 completion:(id /* block */)arg2;
- (void)sendAnnouncement:(id)arg1 toHomeWithID:(id)arg2 completion:(id /* block */)arg3;
- (void)sendAnnouncement:(id)arg1 toHomeWithName:(id)arg2 completion:(id /* block */)arg3;
- (void)sendAnnouncement:(id)arg1 toRoomsWithIDs:(id)arg2 andZonesWithIDs:(id)arg3 inHomeWithID:(id)arg4 completion:(id /* block */)arg5;
- (void)sendAnnouncement:(id)arg1 toRoomsWithNames:(id)arg2 andZonesWithNames:(id)arg3 completion:(id /* block */)arg4;
- (void)sendAnnouncement:(id)arg1 toRoomsWithNames:(id)arg2 andZonesWithNames:(id)arg3 inHomeWithName:(id)arg4 completion:(id /* block */)arg5;
- (void)sendReply:(id)arg1 forAnnouncement:(id)arg2 completion:(id /* block */)arg3;

@end
