/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSAccessory : NSObject {
    NSString * _endpointUUID;
    UIColor * _primaryColor;
    UIColor * _secondaryColor;
    bool  _shouldLockScreenWhenAttached;
    long long  _type;
}

@property (nonatomic, retain) NSString *endpointUUID;
@property (nonatomic, retain) UIColor *primaryColor;
@property (nonatomic, retain) UIColor *secondaryColor;
@property (nonatomic, readonly) bool shouldDelayAnimation;
@property (nonatomic) bool shouldLockScreenWhenAttached;
@property (nonatomic, readonly) bool shouldShowAnimation;
@property (nonatomic) long long type;

+ (id)accessoryWithType:(long long)arg1 primaryColor:(id)arg2 secondoryColor:(id)arg3;

- (void).cxx_destruct;
- (long long)accessoryTypeFromDictionary:(id)arg1;
- (id)accessoryTypeString;
- (id)colorForP3ColorData:(id)arg1;
- (id)description;
- (id)endpointUUID;
- (id)initWithDictionary:(id)arg1 endpointUUID:(id)arg2;
- (id)primaryColor;
- (id)secondaryColor;
- (void)setEndpointUUID:(id)arg1;
- (void)setPrimaryColor:(id)arg1;
- (void)setSecondaryColor:(id)arg1;
- (void)setShouldLockScreenWhenAttached:(bool)arg1;
- (void)setType:(long long)arg1;
- (bool)shouldDelayAnimation;
- (bool)shouldLockScreenWhenAttached;
- (bool)shouldShowAnimation;
- (long long)type;

@end
