/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSAccessoryConfiguration : NSObject {
    struct CGSize { 
        double width; 
        double height; 
    }  _boltSize;
    double  _chargePercentFont;
    double  _lineWidth;
    double  _ringDiameter;
    bool  _showBolt;
    double  _splashRingDiameter;
    double  _splashRingDiameterSizeXFactor;
    double  _splashRingDiameterSizeXXFactor;
    double  _splashRingDiameterSizeXXXFactor;
    bool  _staticViewNeeded;
    double  _staticViewRingDiameter;
    double  _walletBottomOffset;
    double  _walletCornerRadius;
    struct CGSize { 
        double width; 
        double height; 
    }  _walletSize;
}

@property (nonatomic) struct CGSize { double x1; double x2; } boltSize;
@property (nonatomic) double chargePercentFont;
@property (nonatomic) double lineWidth;
@property (nonatomic) double ringDiameter;
@property (nonatomic, readonly) bool showBolt;
@property (nonatomic) double splashRingDiameter;
@property (nonatomic) double splashRingDiameterSizeXFactor;
@property (nonatomic) double splashRingDiameterSizeXXFactor;
@property (nonatomic) double splashRingDiameterSizeXXXFactor;
@property (nonatomic) bool staticViewNeeded;
@property (nonatomic) double staticViewRingDiameter;
@property (nonatomic, readonly) double walletBottomOffset;
@property (nonatomic, readonly) double walletCornerRadius;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } walletSize;

+ (id)defaultConfiguration;
+ (id)staticViewConfiguration;

- (struct CGSize { double x1; double x2; })boltSize;
- (double)chargePercentFont;
- (id)initWithStaticViewNeeded:(bool)arg1;
- (double)lineWidth;
- (double)ringDiameter;
- (void)setBoltSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setChargePercentFont:(double)arg1;
- (void)setLineWidth:(double)arg1;
- (void)setRingDiameter:(double)arg1;
- (void)setSplashRingDiameter:(double)arg1;
- (void)setSplashRingDiameterSizeXFactor:(double)arg1;
- (void)setSplashRingDiameterSizeXXFactor:(double)arg1;
- (void)setSplashRingDiameterSizeXXXFactor:(double)arg1;
- (void)setStaticViewNeeded:(bool)arg1;
- (void)setStaticViewRingDiameter:(double)arg1;
- (void)setValuesWithStaticViewNeeded:(bool)arg1;
- (bool)showBolt;
- (double)splashRingDiameter;
- (double)splashRingDiameterSizeXFactor;
- (double)splashRingDiameterSizeXXFactor;
- (double)splashRingDiameterSizeXXXFactor;
- (bool)staticViewNeeded;
- (double)staticViewRingDiameter;
- (double)walletBottomOffset;
- (double)walletCornerRadius;
- (struct CGSize { double x1; double x2; })walletSize;

@end
