/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSAccessorySleeveViewController : CSAccessoryViewController <BCBatteryDeviceObserving> {
    BCBatteryDeviceController * _batteryDeviceController;
    bool  _chargingAnimationVisible;
    <SBFDateProviding> * _dateProvider;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _dateViewBounds;
    SBFLockScreenDateViewController * _dateViewController;
    SBFLockScreenDateViewController * _secodaryDateViewController;
    CSAccessorySleeveView * _sleeveView;
}

@property (nonatomic, retain) BCBatteryDeviceController *batteryDeviceController;
@property (nonatomic) bool chargingAnimationVisible;
@property (nonatomic, retain) <SBFDateProviding> *dateProvider;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } dateViewBounds;
@property (nonatomic, retain) SBFLockScreenDateViewController *dateViewController;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SBFLockScreenDateViewController *secodaryDateViewController;
@property (nonatomic, retain) CSAccessorySleeveView *sleeveView;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)accessoryView;
- (double)animationDurationBeforeDismissal;
- (id)batteryDeviceController;
- (double)chargingAnimationDuration;
- (bool)chargingAnimationVisible;
- (void)connectedDevicesDidChange:(id)arg1;
- (id)dateProvider;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })dateViewBounds;
- (id)dateViewController;
- (bool)hasChargingAnimation;
- (id)initWithAccessory:(id)arg1;
- (bool)isStatic;
- (id)secodaryDateViewController;
- (void)setBatteryDeviceController:(id)arg1;
- (void)setChargingAnimationVisible:(bool)arg1;
- (void)setDateProvider:(id)arg1;
- (void)setDateViewBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setDateViewController:(id)arg1;
- (void)setSecodaryDateViewController:(id)arg1;
- (void)setSleeveView:(id)arg1;
- (bool)showingChargingAnimation;
- (id)sleeveView;
- (void)transitionChargingViewVisible:(bool)arg1 chargingInfo:(id)arg2;
- (void)updateViewWithBatteryCharging:(bool)arg1;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
