/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoverSheet.framework/CoverSheet
 */

@interface CSLockScreenChargingSettings : PTSettings {
    double  _ironmanAnimationBlockingDurationAfterBootInSeconds;
    double  _ironmanAnimationDelayInMilliseconds;
    bool  _showWirelessAndAccessoryAnimations;
    long long  _wiredChargingAnimationType;
    long long  _wirelessChargingAnimationType;
    double  _wirelessChargingDebounceDurationInSeconds;
}

@property (nonatomic) double ironmanAnimationBlockingDurationAfterBootInSeconds;
@property (nonatomic) double ironmanAnimationDelayInMilliseconds;
@property (nonatomic) bool showWirelessAndAccessoryAnimations;
@property (nonatomic) long long wiredChargingAnimationType;
@property (nonatomic) long long wirelessChargingAnimationType;
@property (nonatomic) double wirelessChargingDebounceDurationInSeconds;

+ (id)settingsControllerModule;

- (long long)accessoryTypeForAnimationType:(long long)arg1;
- (double)ironmanAnimationBlockingDurationAfterBootInSeconds;
- (double)ironmanAnimationDelayInMilliseconds;
- (void)setDefaultValues;
- (void)setIronmanAnimationBlockingDurationAfterBootInSeconds:(double)arg1;
- (void)setIronmanAnimationDelayInMilliseconds:(double)arg1;
- (void)setShowWirelessAndAccessoryAnimations:(bool)arg1;
- (void)setWiredChargingAnimationType:(long long)arg1;
- (void)setWirelessChargingAnimationType:(long long)arg1;
- (void)setWirelessChargingDebounceDurationInSeconds:(double)arg1;
- (bool)showWirelessAndAccessoryAnimations;
- (long long)wiredChargingAnimationType;
- (long long)wirelessChargingAnimationType;
- (double)wirelessChargingDebounceDurationInSeconds;

@end
